# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: '0.1$(Rev:.r)'

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI: 'true'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis configuration'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'jacksondr5'
    scannerMode: 'CLI'
    configMode: 'file'
    configFile: 'sonarcloud.properties'

- task: Npm@1
  inputs:
    command: 'ci'
  displayName: 'Install Dependencies'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: 'Build Project'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test'
  displayName: 'Run Unit Tests'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'