# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'ci'
  displayName: 'Install Dependencies'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'build'
  displayName: 'Build Project'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test'
  displayName: 'Run Unit Tests'